### ISSUE TITLE
Why WechatAppMessageType and WechatMessageType are private?

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty-puppet#20]
I would like to use the type to map the message, but I found they are private and not being exported. Should I create my own copy of types in `wechaty-puppet-padchat` or share this one? I think the types should be shared across all platforms, so I think it would be better to make it public and exported it from `wechaty-puppet`

**Comment by windmemory** [comment]
ping @zixia

**Comment by zixia** [comment]
Yes, they are private is because that I'm not sure those numbers are same across all the platforms.

As far as we know today, the Web and iPad protocol are sharing those numbers in API, but we can not guarantee others are, even I guess they should be.

So I put them into puppet for comment only.

Please define them in your puppet implementation and do not rely on the puppet.

**Comment by windmemory** [comment]
Got it, will do.
