### ISSUE TITLE
Question: why remove start and stop event on puppet

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty-puppet#8]
* What's the reason behind this change? 
* Without the start and stop event, how to know when the puppet is started and stopped?

**Comment by zixia** [comment]
`start` / `stop` event is removed because they are totally useless.

You can get to know the puppet start/stop state from the `state` property:

1. `puppet.state.on() === 'pending'` will be true when the puppet is starting
1. `puppet.state.on() === true` will be true when the puppet is started
1. `puppet.state.off() === 'pending'` will be true when the puppet is stoping
1. `puppet.state.off() === true' will be true when the puppet is stopped

Learn more about the `puppet.state` at <https://github.com/zixia/state-switch>

**Comment by windmemory** [comment]
Got it, that makes sense. Thanks for the explanation.
